atykhonov/google-translate

- google-translate-tk.el
Sorry for the mistake.
Thank you.
> Fix google-translate--lsh

- .bump-version.el
- Makefile
- features/google-translate-default-ui.feature
- features/google-translate-smooth-ui.feature
- google-translate-core-ui.el
- google-translate-default-ui.el
- google-translate-pkg.el
- google-translate-smooth-ui.el
- google-translate-tk.el
- google-translate.el
Feature for listening to translation in target language #46
> Translation listening target language

- google-translate-tk.el
- test/google-translate-tk-test.el
Hello,
I tried translating the python code into elisp again.
It works on my environment.
I hope this works out.
Thank you.
> Fix google-translate--gen-tk

- google-translate-tk.el
It seems "Connection: close" would be needed.
Thank you.
>  Fix google-translate--get-b-d1

- README.md
- google-translate-core-ui.el
- google-translate-default-ui.el
- google-translate-smooth-ui.el
Implementation for requested feature #44 .
> Implement input method auto toggling for default ui.

- google-translate-core-ui.el
> Fix translation listening when source language equals to auto.

- README.md
Fix quotation marks for a correct markdown display.
> Fix quotation marks in README.md

- google-translate-core-ui.el
- google-translate-default-ui.el
This make user easy to read.
It looks like this:
> Provide a new way to translate buffer paragraph by paragraph.

- google-translate-core.el
> fix #98 empty info sequence error

- google-translate-core.el
- google-translate-tk.el
For customize google translate url.
> Change defvar to defcustom

- google-translate-default-ui.el
> format code

- google-translate-core-ui.el
- google-translate-core.el
Applied @OGAWAHirofumi patch, confirmed the issue and tested it works fine.
> Fix #66 long text translate_tts is failed issue

- google-translate-core-ui.el
Improved the option `google-translate-output-destination` docstring.
Added some new value of new added output targets.
> improve option google-translate-output-destination docstring

- google-translate-core.el
Add additional request url parameter "hl" which set language from host.
> Fix #64 when current-iso639-language is set to other languages

- README.md
- google-translate-core-ui.el
- google-translate-core.el
- google-translate-default-ui.el
- google-translate-smooth-ui.el
- google-translate-tk.el
- google-translate.el
Improve the option `google-translate-output-destination` for better customize support.
> Improve option type spec

- .bump-version.el
- Makefile
- google-translate-core-ui.el
- google-translate-core.el
- google-translate-default-ui.el
- google-translate-pkg.el
- google-translate-smooth-ui.el
- google-translate-tk.el
- google-translate.el
Merged some PR and did some small improvements, and two minor feature commands.
I think it's time to bump version to release.
> bump version to 0.12.0

- .github/workflows/elisp.yml
- google-translate-default-ui.el
Try to add CI test for this project.
Don't know how to test whether it works.
> Add CI test

- .dir-locals.el
- .github/workflows/elisp.yml
- google-translate-core-ui.el
- google-translate-core.el
- google-translate-default-ui.el
- google-translate.el
> fix CI error seq-empty-p depend on emacs version "25.1"

- google-translate.el
> Add popup to Package-Requires

- google-translate-core-ui.el
Fixes https://github.com/atykhonov/google-translate/issues/127
> Fix function name

- google-translate-core-ui.el
More fixing for https://github.com/atykhonov/google-translate/issues/126
> Use the function "cl-loop" and "cl-incf" in cl-lib

- google-translate-smooth-ui.el
> Put last used translation direction on top.

- google-translate-core-ui.el
> add missing facemenu dependency

- google-translate-core-ui.el
Fix #97, And PR #102 
I think this enhancement is a helpful convinient thing. Should be useful in some ways.
> Fix #97, Add translation to kill-ring for inserting
